server:
  port: 81

#单机服务端不需要注册服务，查询服务，集群仍然需要
#单机降低renewal-percent-threshold值，默认0.85
eureka:
  server:
    renewal-percent-threshold: 0.49
  instance:
    hostname: ekServer2
  client:
   # registerWithEureka: false
   # fetchRegistry: false
    serviceUrl:
      defaultZone: http://ekServer1:80/eureka/
spring:
  application:
    name: ekServer2
