server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/homework?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  #热部署生效、设置重启的目录,添加那个目录的文件需要restart
  devtools:
    restart:
      enabled: true
      additional-exclude: WEB-INF/**
      additional-paths: src/main/java

mybatis:
  mapperLocations: classpath:static/mapper/*.xml
  typeAliasesPackage: com.kong.demo1.entity

#执行的sql打印到控制台
logging:
  level:
    com:
      joy: DEBUG
