server:
  port: 80

#单机服务端不需要注册服务，查询服务，集群仍然需要
#单机降低renewal-percent-threshold值，默认0.85
#指定该服务向ekserver2注册
eureka:
  server:
    renewal-percent-threshold: 0.49
  instance:
    hostname: ekServer1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://ekServer1:80/eureka/
spring:
  application:
    name: ekServer1